feat: add KubectLayer and release as @aws-cdk/lambda-layer-kubectl-v29
cdklabs/awscdk-asset-kubectl pull request #546
Opened 2024-02-04 06:15 UTC by awsdataarchitect

2024-02-04 10:51 UTC, awsdataarchitect commented
@pahud  @kaizencc can you review and approve please. The CDK support for v1.29 is still outstanding

2024-02-05 16:00 UTC, kaizencc reviewed
@awsdataarchitect, I've created the `kubectl-v29/main` branch for you. I believe you will still need to update the snapshots to get this PR to build: https://github.com/cdklabs/awscdk-asset-kubectl/blob/kubectl-v28/main/CONTRIBUTING.md#contributing-a-new-kubectl-asset

Edit: nevermind i see you already have. but the build is failing for something else

2024-02-05 17:42 UTC, awsdataarchitect commented
yarn build was failing locally

yarn build                             
yarn run v1.22.21
$ npx projen build
👾 build » default | ts-node --project tsconfig.dev.json .projenrc.ts
👾 build » pre-compile | layer/build.sh
>> Building AWS Lambda layer inside a docker image...
[+] Building 0.5s (14/14) FINISHED                                                                                          docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                        0.0s
 => => transferring dockerfile: 891B                                                                                                        0.0s
 => [internal] load metadata for public.ecr.aws/lambda/provided:latest                                                                      0.5s
 => [internal] load .dockerignore                                                                                                           0.0s
 => => transferring context: 49B                                                                                                            0.0s
 => [ 1/11] FROM public.ecr.aws/lambda/provided:latest@sha256:de16980aa2c70c7bcd3324b788d90c3e85a62f128c5f79919ab312b6286c94f0              0.0s
 => CACHED [ 2/11] RUN mkdir -p /opt                                                                                                        0.0s
 => CACHED [ 3/11] WORKDIR /tmp                                                                                                             0.0s
 => CACHED [ 4/11] RUN dnf update -y     && dnf install -y zip unzip wget tar gzip                                                          0.0s
 => CACHED [ 5/11] RUN mkdir -p /opt/kubectl                                                                                                0.0s
 => CACHED [ 6/11] RUN cd /opt/kubectl && curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.29.1/bin/linux/amd64/kube  0.0s
 => CACHED [ 7/11] RUN chmod +x /opt/kubectl/kubectl                                                                                        0.0s
 => CACHED [ 8/11] RUN mkdir -p /tmp/helm && wget -qO- https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz | tar -xvz -C /tmp/helm          0.0s
 => CACHED [ 9/11] RUN mkdir -p /opt/helm && cp /tmp/helm/linux-amd64/helm /opt/helm/helm                                                   0.0s
 => CACHED [10/11] RUN cd /opt     && zip --symlinks -r ../layer.zip *     && echo "/layer.zip is ready"     && ls -alh /layer.zip;         0.0s
 => exporting to image                                                                                                                      0.0s
 => => exporting layers                                                                                                                     0.0s
 => => writing image sha256:b0c83a4e2b9d5794c40895ee9cb55fb27d29357c777fc936f29b7b3873e16ce3                                                0.0s
 => => naming to docker.io/library/aws-lambda-layer                                                                                         0.0s

What's Next?
  1. Sign in to your Docker account → docker login
  2. View a summary of image vulnerabilities and recommendations → docker scout quickview
>> Extrating layer.zip from the build container...
                               Successfully copied 31.7MB to awscdk-asset-kubectl/lib/layer.zip
>> Stopping container...
9a6adc4afb404335647dd5a64e5bf4742dc35eb05e4d4bbbb014f84e3850988c
>> lib/layer.zip is ready
👾 build » compile | jsii --silence-warnings=reserved-word
[2024-02-05T12:17:26.682] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
node_modules/@types/node/ts4.8/crypto.d.ts:3495:17 - error TS1110: Type expected.

3495     type UUID = `${string}-${string}-${string}-${string}-${string}`;
                     ~~~
👾 Task "build » compile" failed when executing "jsii --silence-warnings=reserved-word" (cwd: /Users/vivekvelso/Documents/opensource/awscdk-asset-kubectl)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

2024-02-05 23:21 UTC, awsdataarchitect commented
@kaizencc  All tests are passing now. Please approve.  <img width="1699" alt="Screenshot 2024-02-05 at 6 18 48 PM" src="https://github.com/cdklabs/awscdk-asset-kubectl/assets/34197929/d47bd840-87bd-4613-aa37-56617d799034">

2024-02-06 16:57 UTC, awsdataarchitect commented
Just a small followup @kaizencc  @pahud @robertd @udaypant @cgarvis

2024-02-07 22:54 UTC, robertd commented
@kaizencc Can we ship this one?

2024-02-09 00:48 UTC, kaizencc commented on yarn.lock
I cant approve until these changes in this file are gone. I tried updating it myself but git chokes because your branch name is a "protected" branch

2024-02-09 00:49 UTC, kaizencc requested changes
This looks good except for the yarn.lock changes. The registry should stay yarnpkg

2024-02-09 16:56 UTC, kaizencc approved these changes
Thanks @awsdataarchitect!

2024-02-09 17:02 UTC, merged