chore: explain how to contribute new kubectl version assets in the contributing guide
cdklabs/awscdk-asset-kubectl pull request #8
Opened 2022-09-21 18:33 UTC by kaizencc

Once this is approved, my plan is to backport this to `kubectl-v21/main` and `kubectl-v20/main`.

2022-09-21 18:33 UTC, kaizencc reviewed
Once this is approved, my plan is to backport this to `kubectl-v21/main` and `kubectl-v20/main`.

2022-09-27 21:05 UTC, kaizencc commented
@Mergifyio backport kubectl-v21/main kubectl-v20/main

2022-09-28 05:31 UTC, madeline-k requested changes

2022-09-28 05:31 UTC, madeline-k commented on CONTRIBUTING.md
> +    - change `SPEC_VERSION` in `.projenrc.js` to reflect the new minor version of kubectl.
Explain how to choose a helm version that is compatible. Link to the relevant docs.

2022-10-17 23:01 UTC, madeline-k approved these changes

2022-10-17 23:14 UTC, merged